//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public boleto()
        {
            this.bus1 = new HashSet<bus>();
        }
    
        public int id_boleto { get; set; }
        public Nullable<int> id_pasajero { get; set; }
        public Nullable<int> id_bus { get; set; }
        public Nullable<int> id_ruta { get; set; }
        public Nullable<System.DateTime> horasalida { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
        public string asientos { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> id_vendedor { get; set; }
    
        public virtual vendedor vendedor { get; set; }
        public virtual pasajero pasajero { get; set; }
        public virtual bus bus { get; set; }
        public virtual rutas rutas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bus> bus1 { get; set; }
    }
}
