//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class operador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operador()
        {
            this.bus = new HashSet<bus>();
        }
    
        public int id_operador { get; set; }
        public string nombres { get; set; }
        public Nullable<int> cedula { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> id_bus { get; set; }
        public Nullable<int> sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bus> bus { get; set; }
        public virtual bus bus1 { get; set; }
        public virtual sexo sexo1 { get; set; }
    }
}
